# Generated by Django 6.1 on 2026-08-16 10:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Имя товара')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=30, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена товара')),
                ('stock', models.BigIntegerField(default=0, verbose_name='Количество товара на складе')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания товара')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-created_at'],
            },
        ),
    ]
